/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import modelos.Funcionario;
/**
 *
 * @author tabaxco
 */
public class Funcionario_View extends javax.swing.JPanel {

    /**
     * Creates new form Funcionario_View
     */
    public Funcionario_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textCargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textIDF = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        altButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        readButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textSalario = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nome");

        jLabel2.setText("Telefone");

        jLabel3.setText("Cargo");

        jLabel4.setText("Id do Funcionário");

        addButton.setText("Adicionar");
        addButton.addActionListener(this::addButtonActionPerformed);

        altButton.setText("Alterar");
        altButton.addActionListener(this::altButtonActionPerformed);

        delButton.setText("Deletar");
        delButton.addActionListener(this::delButtonActionPerformed);

        readButton.setText("Buscar");
        readButton.addActionListener(this::readButtonActionPerformed);

        jLabel5.setText("Salário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(199, 199, 199))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(altButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(101, 101, 101)
                .addComponent(jLabel2)
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(textCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textIDF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(altButton)
                    .addComponent(delButton)
                    .addComponent(readButton))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String nome = textNome.getText();
        String telefone = textTelefone.getText();
        String cargo = textCargo.getText();
        double salario = Double.parseDouble(textSalario.getText());
        
        Funcionario addFuncionario = new Funcionario();
        
        addFuncionario.setNome(nome);
        addFuncionario.setCargo(cargo);
        addFuncionario.setTelefone(telefone);
        addFuncionario.setSalario(salario);
        
        try {
            DAO.Funcionario_DAO.inserir(addFuncionario);
            JOptionPane.showMessageDialog(null, "Funcionário inserido corretamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir funcionário: " + e.getMessage());
        }
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void altButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altButtonActionPerformed
        int id = Integer.parseInt(textIDF.getText());
        String nome = textNome.getText();
        String telefone = textTelefone.getText();
        String cargo = textCargo.getText();
        double salario = Double.parseDouble(textSalario.getText());
        
        Funcionario altFuncionario = new Funcionario();
        
        altFuncionario.setID_Funcionario(id);
        altFuncionario.setNome(nome);
        altFuncionario.setCargo(cargo);
        altFuncionario.setTelefone(telefone);
        altFuncionario.setSalario(salario);
        
        try {
            DAO.Funcionario_DAO.atualizar(altFuncionario);
            JOptionPane.showMessageDialog(null, "Funcionário atualizado corretamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro.");
        }
        
    }//GEN-LAST:event_altButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        int id = Integer.parseInt(textIDF.getText());
        
        Funcionario delFuncionario = new Funcionario();
        
        delFuncionario.setID_Funcionario(id);
        
        try {
            DAO.Funcionario_DAO.deletar(delFuncionario);
            JOptionPane.showMessageDialog(null, "Funcionário deletado corretamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro.");
        }
    }//GEN-LAST:event_delButtonActionPerformed

    private void readButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonActionPerformed
        int id = Integer.parseInt(textIDF.getText());
        
        Funcionario readFuncionario = new Funcionario();
        readFuncionario.setID_Funcionario(id);
        
        try {
            readFuncionario = DAO.Funcionario_DAO.buscarPorId(readFuncionario);
            
         if (readFuncionario != null)   {
             textNome.setText(readFuncionario.getNome());
             textCargo.setText(readFuncionario.getCargo());
             textSalario.setText(Double.toString(readFuncionario.getSalario()));
             textTelefone.setText(readFuncionario.getTelefone());
         }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro.");
        }
    }//GEN-LAST:event_readButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton altButton;
    private javax.swing.JButton delButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton readButton;
    private javax.swing.JTextField textCargo;
    private javax.swing.JTextField textIDF;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSalario;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
