/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import modelos.Funcionario;
/**
 *
 * @author tabaxco
 */
public class Funcionario_View extends javax.swing.JPanel {

    /**
     * Creates new form Funcionario_View
     */
    public Funcionario_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textTelefone = new javax.swing.JTextField();
        textFuncao = new javax.swing.JLabel();
        textFunc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textIDF = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        altButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        readButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textSalario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textDepartamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textUser = new javax.swing.JTextField();
        textData = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textSenha = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nome");

        jLabel2.setText("Telefone");

        textFuncao.setText("Função");

        textFunc.addActionListener(this::textFuncActionPerformed);

        jLabel4.setText("Id do Funcionário");

        addButton.setText("Adicionar");
        addButton.addActionListener(this::addButtonActionPerformed);

        altButton.setText("Alterar");
        altButton.addActionListener(this::altButtonActionPerformed);

        delButton.setText("Deletar");
        delButton.addActionListener(this::delButtonActionPerformed);

        readButton.setText("Buscar");
        readButton.addActionListener(this::readButtonActionPerformed);

        jLabel5.setText("Salário");

        jLabel6.setText("Departamento");

        jLabel3.setText("E-mail");

        jLabel7.setText("Usuário");

        textData.setEnabled(false);

        jLabel8.setText("Data de Contratação");

        jLabel9.setText("Senha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2)
                                .addGap(77, 77, 77)
                                .addComponent(textFuncao)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(textFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textDepartamento)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textIDF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(addButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(altButton))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addComponent(jLabel7))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(delButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(readButton))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(179, 179, 179)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(textFuncao)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(textIDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(altButton)
                    .addComponent(delButton)
                    .addComponent(readButton))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String nome = textNome.getText();
        String telefone = textTelefone.getText();
        String cargo = textFunc.getText();
        double salario = Double.parseDouble(textSalario.getText());
        String departamento = textDepartamento.getText();
        String email = textEmail.getText();
        String usuario = textUser.getText();
        String senha = textSenha.getText();
        java.sql.Date hoje = new java.sql.Date(System.currentTimeMillis());
        
        Funcionario addFuncionario = new Funcionario();
        
        addFuncionario.setNome(nome);
        addFuncionario.setCargo(cargo);
        addFuncionario.setTelefone(telefone);
        addFuncionario.setSalario(salario);
        addFuncionario.setDepartamento(departamento);
        addFuncionario.setEmail(email);
        addFuncionario.setUsuario(usuario);
        addFuncionario.setSenha(senha);
        addFuncionario.setDataCadastro(hoje);
        
        try {
            DAO.Funcionario_DAO.inserir(addFuncionario);
            JOptionPane.showMessageDialog(null, "Funcionário inserido corretamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir funcionário: " + e.getMessage());
        }
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void altButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altButtonActionPerformed
        int id = Integer.parseInt(textIDF.getText());
        String nome = textNome.getText();
        String telefone = textTelefone.getText();
        String cargo = textFunc.getText();
        double salario = Double.parseDouble(textSalario.getText());
        String departamento = textDepartamento.getText();
        String email = textEmail.getText();
        String usuario = textUser.getText();
        String senha = textSenha.getText();
        
        Funcionario altFuncionario = new Funcionario();
        
        altFuncionario.setID_Funcionario(id);
        altFuncionario.setNome(nome);
        altFuncionario.setCargo(cargo);
        altFuncionario.setTelefone(telefone);
        altFuncionario.setSalario(salario);
        altFuncionario.setDepartamento(departamento);
        altFuncionario.setEmail(email);
        altFuncionario.setUsuario(usuario);
        altFuncionario.setSenha(senha);
        
        try {
            DAO.Funcionario_DAO.atualizar(altFuncionario);
            JOptionPane.showMessageDialog(null, "Funcionário atualizado corretamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro.");
        }
        
    }//GEN-LAST:event_altButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        int id = Integer.parseInt(textIDF.getText());
        
        Funcionario delFuncionario = new Funcionario();
        
        delFuncionario.setID_Funcionario(id);
        
        try {
            DAO.Funcionario_DAO.deletar(delFuncionario);
            JOptionPane.showMessageDialog(null, "Funcionário deletado corretamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro.");
        }
    }//GEN-LAST:event_delButtonActionPerformed

    private void readButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonActionPerformed
        int id = Integer.parseInt(textIDF.getText());
        
        Funcionario readFuncionario = new Funcionario();
        readFuncionario.setID_Funcionario(id);
        
        try {
            readFuncionario = DAO.Funcionario_DAO.buscarPorId(readFuncionario);
            
         if (readFuncionario != null)   {
             textNome.setText(readFuncionario.getNome());
             textFunc.setText(readFuncionario.getCargo());
             textSalario.setText("R$"+ Double.toString(readFuncionario.getSalario()));
             textEmail.setText(readFuncionario.getEmail());
             textTelefone.setText(readFuncionario.getTelefone());
             textDepartamento.setText(readFuncionario.getDepartamento());
             if (readFuncionario.getDepartamento() == null) {
                 textDepartamento.setText("Beta Tester");
             }
             
             textUser.setText(readFuncionario.getUsuario());
             textSenha.setText(readFuncionario.getSenha());
             textData.setText(readFuncionario.getDataCadastro().toString());
         }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro.");
        }
    }//GEN-LAST:event_readButtonActionPerformed

    private void textFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton altButton;
    private javax.swing.JButton delButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton readButton;
    private javax.swing.JTextField textData;
    private javax.swing.JTextField textDepartamento;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textFunc;
    private javax.swing.JLabel textFuncao;
    private javax.swing.JTextField textIDF;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSalario;
    private javax.swing.JTextField textSenha;
    private javax.swing.JTextField textTelefone;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
}
